name: Tugas Pipeline DevSecOps
on: [push]
jobs:
  unit-test:
    name: Unit Test (pytest)
    runs-on: [self-hosted, Linux, x64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi

      - name: Run Pytest
        run: pytest
  sast-bandit:
    name: SAST Scan (Bandit)
    runs-on: [self-hosted, Linux, x64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r . -ll -f json -o bandit-report.json
  sca-pip-audit:
    name: SCA (pip-audit)
    runs-on: [self-hosted, Linux, x64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pip-audit

      - name: Run pip-audit
        run: pip-audit -r requirements.txt
  secret-scan:
    name: Secret Scan (Gitleaks)
    runs-on: [self-hosted, Linux, x64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-format json --report-path gitleaks-report.json
  build-and-push:
    name: Build & Push Docker Image
    runs-on: [self-hosted, Linux, x64]
    needs: [unit-test, sast-bandit, sca-pip-audit, secret-scan]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-devsecops:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-devsecops:latest
